### ISSUE TITLE
avoid_using_api: Lint Default Constructor Only

### ISSUE THREAD

**Issue by getBoolean** [solid-software/solid_lints#126]
While using the lint I noticed I missed an edge case, it is not possible to lint only the default constructor. it will always lint all usages of the class

Potential usage:

```yaml
custom_lint:
  rules:
    - avoid_using_api:
      entries:
        # Add parentheses to lint only default constructor, use `identifier` for named constructors
        - class_name: Border()
          source: package:flutter
          reason: Use `BorderDirectional` instead.
```

Not sure if this is the best way to implement it, and I could see it being confusing if named constructors (ie `class_name: Border.all()`) didn't also work. Thoughts?

I can implement this.

**Comment by getBoolean** [comment]
I also want to explore linting constructor fields

**Comment by illia-romanenko** [comment]
Yes - that should be it. Not sure what `left` means here but just `()` should be the best.

**Comment by getBoolean** [comment]
`left` was a constructor parameter in the default constructor. Seems a bit confusing putting it in parentheses, so maybe a separate input field `parameter` would make it clear

The intent for my second comment was to only lint usage of a specific parameter in a constructor (or method)

```dart
final border = const Border(left: 4.0); // LINT
final border2 = const Border(top: 4.0); // Okay
```

```yaml
custom_lint:
  rules:
    - avoid_using_api:
      entries:
        - class_name: Border
          identifier: ()
          parameter: left
          source: package:flutter
          reason: Use `BorderDirectional(start)` instead.
```
