### ISSUE TITLE
Allow disabling `avoid_returning_widgets` for certain methods

### ISSUE THREAD

**Issue by danylo-safonov-solid** [solid-software/solid_lints#131]
e.g. `InheritedWidget.of`, `SingleChildWidget.buildWithChild`

**Comment by solid-vovabeloded** [comment]
Let's make the API similar to one we are using for avoid_using_api rule: 

```yaml
     - avoid_returning_widgets:
       exclude:
         - identifier: wait
           class_name: Future
           source: dart:async
```
